name: Build bindings for Linux、macos、windows releases

on: [push]

jobs: 
  build-x64:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        arch: [ x64 ]
        node: [ 16.13.0 ]

    runs-on: ${{ matrix.os }}

    env:
      ARCH: ${{matrix.arch}}
      VERSION: ${{matrix.node}}
      RUNTIME: node
      LIBC: glibc

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[16.4,17.4)'
        if: ${{matrix.os == 'windows-latest'}}

      - name: Build
        run: grpc/${{matrix.os}}-build.sh
        if: ${{matrix.os != 'windows-latest'}}

      - name: Build
        run: grpc/${{matrix.os}}-build.bat
        if: ${{matrix.os == 'windows-latest'}}

